### ISSUE TITLE
About the low-dose simulation dataset used in the text

### ISSUE THREAD

**Issue by DzChen-BIT** [qgao21/CoreDiff#15]
Thank you for sharing and actively communicating about the model code. I was performing a low-dose CT simulation based on “A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan” and noticed that the range of values in the Sinogram has a significant impact on the results. I have encountered a lot of problems in this process. Could you please share the code of the low-dose simulation program or the simulated low-dose dataset used in the following article?

感谢您关于模型代码的分享和积极交流，我在根据“A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan”进行低剂量CT模拟时注意到Sinogram的值域范围对结果影响很大，在这个过程中遇到了很多问题。请问可否分享下文中使用的低剂量模拟程序代码或者模拟的低剂量数据集，万分感谢！

**Comment by kklay11** [comment]
> Thank you for sharing and actively communicating about the model code. I was performing a low-dose CT simulation based on “A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan” and noticed that the range of values in the Sinogram has a significant impact on the results. I have encountered a lot of problems in this process. Could you please share the code of the low-dose simulation program or the simulated low-dose dataset used in the following article?
> 
> 感谢您关于模型代码的分享和积极交流，我在根据“A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan”进行低剂量CT模拟时注意到Sinogram的值域范围对结果影响很大，在这个过程中遇到了很多问题。请问可否分享下文中使用的低剂量模拟程序代码或者模拟的低剂量数据集，万分感谢！

您好，我想问一下模拟低剂量ct用到的工具和数据相关问题。需要的数据是要ct的投影数据吗，还有是如何进行模拟的

**Comment by zhenneidazhi1022** [comment]
> Thank you for sharing and actively communicating about the model code. I was performing a low-dose CT simulation based on “A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan” and noticed that the range of values in the Sinogram has a significant impact on the results. I have encountered a lot of problems in this process. Could you please share the code of the low-dose simulation program or the simulated low-dose dataset used in the following article?
> 
> 感谢您关于模型代码的分享和积极交流，我在根据“A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan”进行低剂量CT模拟时注意到Sinogram的值域范围对结果影响很大，在这个过程中遇到了很多问题。请问可否分享下文中使用的低剂量模拟程序代码或者模拟的低剂量数据集，万分感谢！

把计算中线性衰减系数和距离的单位搞清楚后现在似乎可以了，感谢

**Comment by kklay11** [comment]
> > > Thank you for sharing and actively communicating about the model code. I was performing a low-dose CT simulation based on “A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan” and noticed that the range of values in the Sinogram has a significant impact on the results. I have encountered a lot of problems in this process. Could you please share the code of the low-dose simulation program or the simulated low-dose dataset used in the following article?
> > > 感谢您关于模型代码的分享和积极交流，我在根据“A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan”进行低剂量CT模拟时注意到Sinogram的值域范围对结果影响很大，在这个过程中遇到了很多问题。请问可否分享下文中使用的低剂量模拟程序代码或者模拟的低剂量数据集，万分感谢！
> > 
> > 
> > 您好，我想问一下模拟低剂量ct用到的工具和数据相关问题。需要的数据是要ct的投影数据吗，还有是如何进行模拟的
> 
> @kklay11 我是用的ASTRA toolkit，我的操作如下但可能有误：先把CT图像的HU值图转成线性衰减系数，再投影到sinogram，对sinogram根据成像参数缩放之后处理，再反投影回线性衰减系数，最后转回HU值，

@zhenneidazhi1022 @qgao21 所以不需要用投影数据是吧，我之前的理解可能有误，以为要从投影数据开始。用到的数据只是从NDCT图像开始对吗，对它操作 前投影 获得投影数据，在这个投影数据进行操作以模拟低剂量，然后重建回图像域。不知道我的理解是否正确，期待您的回复。
还有我看作者引用的（https://github.com/smuzd/LD-CT-simulation）是MIRT工具箱，ASTRA toolkit和MIRT都行吗，重建是用FBP就行了吗；这套流程在Windows系统下能用吗

**Comment by kklay11** [comment]
> 1. 您的理解是正确的，不需要使用Mayo 2016数据集提供的投影数据。先对NDCT做前投影，就可以使用[LD-CT-simulation](https://github.com/smuzd/LD-CT-simulation)进行LDCT仿真。
> 2. 使用ASTRA或MIRT都可以，具体前投影和FBP重建函数可以看一下使用手册。ASTRA可以在windows系统下运行，MIRT只能在macOS和Linux系统下运行。

非常感谢您的回复，有一个疑问就是为什么不直接用官方提供的图像和投影数据呢如果仅对于25%剂量而言。

**Comment by qgao21** [comment]
1. 官方提供的是螺旋扫描投影数据，基于扇形束投影进行仿真更为方便。
2. 因为我们在Mayo 2016数据集上进行泛化性验证需要获取其他剂量数据（50%，10%和5%），为保证仿真数据的一致性，对于25%剂量我们也使用了自己仿真的数据。论文的泛化性实验中使用的Mayo 2020低剂量数据是官方提供的低剂量数据。

**Comment by kklay11** [comment]
> 1. 官方提供的是螺旋扫描投影数据，基于扇形束投影进行仿真更为方便。
> 2. 因为我们在Mayo 2016数据集上进行泛化性验证需要获取其他剂量数据（50%，10%和5%），为保证仿真数据的一致性，对于25%剂量我们也使用了自己仿真的数据。论文的泛化性实验中使用的Mayo 2020低剂量数据是官方提供的低剂量数据。

明白了，谢谢您的解答

**Comment by 123-c1** [comment]
> 1. 您的理解是正确的，不需要使用Mayo 2016数据集提供的投影数据。先对NDCT做前投影，就可以使用[LD-CT-simulation](https://github.com/smuzd/LD-CT-simulation)进行LDCT仿真。
> 2. 使用ASTRA或MIRT都可以，具体前投影和FBP重建函数可以看一下使用手册。ASTRA可以在windows系统下运行，MIRT只能在macOS和Linux系统下运行。

您好，对NDCT做前投影，然后用ASTRA进行操作得到加入噪声的低剂量投影对吗，ASTRA好像没有固定的加噪声的操作代码吧？我对加入噪声这个步骤不知道怎么用代码来正确处理，期待您的回复谢谢！

**Comment by kklay11** [comment]
> > 1. 您的理解是正确的，不需要使用Mayo 2016数据集提供的投影数据。先对NDCT做前投影，就可以使用[LD-CT-simulation](https://github.com/smuzd/LD-CT-simulation)进行LDCT仿真。
> > 2. 使用ASTRA或MIRT都可以，具体前投影和FBP重建函数可以看一下使用手册。ASTRA可以在windows系统下运行，MIRT只能在macOS和Linux系统下运行。
> 
> 您好，对NDCT做前投影，然后用ASTRA进行操作得到加入噪声的低剂量投影对吗，ASTRA好像没有固定的加噪声的操作代码吧？我对加入噪声这个步骤不知道怎么用代码来正确处理，期待您的回复谢谢！

加噪声就直接用[LD-CT-simulation](https://github.com/smuzd/LD-CT-simulation)里的pct_ldsino函数吧，主要ASTRA是用来替换代码中mirt工具箱调用的函数的。

**Comment by kklay11** [comment]
> 1. 官方提供的是螺旋扫描投影数据，基于扇形束投影进行仿真更为方便。
> 2. 因为我们在Mayo 2016数据集上进行泛化性验证需要获取其他剂量数据（50%，10%和5%），为保证仿真数据的一致性，对于25%剂量我们也使用了自己仿真的数据。论文的泛化性实验中使用的Mayo 2020低剂量数据是官方提供的低剂量数据。

![Image](https://github.com/user-attachments/assets/792cff30-7ee1-4829-82d3-62b6ada7c953)

![Image](https://github.com/user-attachments/assets/f976061e-073a-4e0f-baee-5929f6581b30)

@qgao21 您好，1，关于低剂量模拟matlab代码中的k值，就是低剂量的比例是吧，如您论文中模拟的50%,25%,5%等是不是直接将k值设为0.5，0.25，0.05呢，2，我模拟的25%（k为0.25）的ct图像，将它和NDCT计算psnr值与真实的LDCT进行比较，psnr相对于TRUE LDCT的值小很多，这是不是和我重建的参数设置有关（这个参数设置应该参考什么设定），很低的话可不可以用来训练

**Comment by qgao21** [comment]
我是直接将k值设为0.5，0.25和0.05。关于2的问题我没有遇到，你可以观察下图像视觉上的噪声和伪影强度和Mayo 2016提供的LDCT是否接近，如果噪声和伪影明显强则需要再检查下仿真设置，I0应设置为1.5e5
